#!/usr/bin/env python3
"""Builds web/assets/topic-icons.svg from tools/topic_icons.json (icons fetched from
game-icons.net's GitHub, CC BY 3.0) and prints the SQL that points each topic at its icon.

Usage: python3 tools/build_topic_icons.py > app/sql/NNN_topic_icons.sql   (for a new migration)
"""
import json, os, re, sys, urllib.request

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
mapping = {k: v for k, v in json.load(open(os.path.join(root, 'tools/topic_icons.json'))).items() if not k.startswith('_')}
cache = os.path.join(root, 'tools/.icon-cache')
os.makedirs(cache, exist_ok=True)

symbols, authors, sql = {}, set(), []
for title, src in mapping.items():
    author, name = src.split('/')
    path = os.path.join(cache, f'{author}__{name}.svg')
    if not os.path.exists(path):
        urllib.request.urlretrieve(f'https://raw.githubusercontent.com/game-icons/icons/master/{src}.svg', path)
    shapes = [d for d in re.findall(r'<path[^>]*d="([^"]+)"', open(path).read()) if d.strip() != 'M0 0h512v512H0z']
    symbols[name] = f'<symbol id="ti-{name}" viewBox="0 0 512 512">' + ''.join(f'<path d="{d}"/>' for d in shapes) + '</symbol>'
    authors.add(author)
    sql.append("UPDATE topics SET icon_key = '%s' WHERE title = '%s';" % (name, title.replace("'", "''")))

with open(os.path.join(root, 'web/assets/topic-icons.svg'), 'w') as f:
    f.write('<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true">\n')
    f.write(f'<!-- Topic icons: game-icons.net, CC BY 3.0, by {", ".join(sorted(authors))} -->\n')
    f.write('\n'.join(symbols[k] for k in sorted(symbols)) + '\n</svg>\n')
print('-- Topic icons (generated by tools/build_topic_icons.py)')
print('\n'.join(sql))
print(f'{len(symbols)} icons; authors: {", ".join(sorted(authors))}', file=sys.stderr)
